export const TMDB_API_CONFIGURATION = {
    TMDB_API_VERSION: process.env.TMDB_API_VERSION,
    TMDB_API_KEY: process.env.TMDB_API_KEY,
    TMDB_API_ACCESS_TOKEN: process.env.TMDB_API_ACCESS_TOKEN,
    TMDB_BASE_URL: process.env.TMDB_BASE_URL,
    TMBD_SECURE_BASE_URL_IMAGE: process.env.TMBD_SECURE_BASE_URL_IMAGE,
};
